version: "3.9"
services:
  tick:
    build: .
    ports:
      - "9001:9001"
    volumes:
      - ./database/:/app/database:rw
    command: node tick.js
    # Without this the container stops if containerd stops, and doesn't
    # start when containerd is started again.
    restart: unless-stopped
  eddn:
    build: .
    volumes:
      - ./database/:/app/database:rw
    command: node EDDN.js
    # Without this the container stops if containerd stops, and doesn't
    # start when containerd is started again.
    restart: unless-stopped
  detector:
    build: .
    volumes:
      - ./database/:/app/database:rw
    command: node detector.js
    # Without this the container stops if containerd stops, and doesn't
    # start when containerd is started again.
    restart: unless-stopped
